name: flutter_facebook_app_links
description: A Flutter plugin to catch deferred deep links from Facebbok ads with FB App Links SDK.
version: 2.0.0+3
homepage: https://github.com/Mapk26/flutter_facebook_app_links

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ^2.2.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: it.remedia.flutter_facebook_app_links
        pluginClass: FlutterFacebookAppLinksPlugin
      ios:
        pluginClass: FlutterFacebookAppLinksPlugin

